require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HardwaretypesController do

  # This should return the minimal set of attributes required to create a valid
  # Hardwaretype. As you add validations to Hardwaretype, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HardwaretypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all hardwaretypes as @hardwaretypes" do
      hardwaretype = Hardwaretype.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hardwaretypes).should eq([hardwaretype])
    end
  end

  describe "GET show" do
    it "assigns the requested hardwaretype as @hardwaretype" do
      hardwaretype = Hardwaretype.create! valid_attributes
      get :show, {:id => hardwaretype.to_param}, valid_session
      assigns(:hardwaretype).should eq(hardwaretype)
    end
  end

  describe "GET new" do
    it "assigns a new hardwaretype as @hardwaretype" do
      get :new, {}, valid_session
      assigns(:hardwaretype).should be_a_new(Hardwaretype)
    end
  end

  describe "GET edit" do
    it "assigns the requested hardwaretype as @hardwaretype" do
      hardwaretype = Hardwaretype.create! valid_attributes
      get :edit, {:id => hardwaretype.to_param}, valid_session
      assigns(:hardwaretype).should eq(hardwaretype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hardwaretype" do
        expect {
          post :create, {:hardwaretype => valid_attributes}, valid_session
        }.to change(Hardwaretype, :count).by(1)
      end

      it "assigns a newly created hardwaretype as @hardwaretype" do
        post :create, {:hardwaretype => valid_attributes}, valid_session
        assigns(:hardwaretype).should be_a(Hardwaretype)
        assigns(:hardwaretype).should be_persisted
      end

      it "redirects to the created hardwaretype" do
        post :create, {:hardwaretype => valid_attributes}, valid_session
        response.should redirect_to(Hardwaretype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hardwaretype as @hardwaretype" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hardwaretype.any_instance.stub(:save).and_return(false)
        post :create, {:hardwaretype => { "name" => "invalid value" }}, valid_session
        assigns(:hardwaretype).should be_a_new(Hardwaretype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hardwaretype.any_instance.stub(:save).and_return(false)
        post :create, {:hardwaretype => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hardwaretype" do
        hardwaretype = Hardwaretype.create! valid_attributes
        # Assuming there are no other hardwaretypes in the database, this
        # specifies that the Hardwaretype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hardwaretype.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => hardwaretype.to_param, :hardwaretype => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested hardwaretype as @hardwaretype" do
        hardwaretype = Hardwaretype.create! valid_attributes
        put :update, {:id => hardwaretype.to_param, :hardwaretype => valid_attributes}, valid_session
        assigns(:hardwaretype).should eq(hardwaretype)
      end

      it "redirects to the hardwaretype" do
        hardwaretype = Hardwaretype.create! valid_attributes
        put :update, {:id => hardwaretype.to_param, :hardwaretype => valid_attributes}, valid_session
        response.should redirect_to(hardwaretype)
      end
    end

    describe "with invalid params" do
      it "assigns the hardwaretype as @hardwaretype" do
        hardwaretype = Hardwaretype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hardwaretype.any_instance.stub(:save).and_return(false)
        put :update, {:id => hardwaretype.to_param, :hardwaretype => { "name" => "invalid value" }}, valid_session
        assigns(:hardwaretype).should eq(hardwaretype)
      end

      it "re-renders the 'edit' template" do
        hardwaretype = Hardwaretype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hardwaretype.any_instance.stub(:save).and_return(false)
        put :update, {:id => hardwaretype.to_param, :hardwaretype => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hardwaretype" do
      hardwaretype = Hardwaretype.create! valid_attributes
      expect {
        delete :destroy, {:id => hardwaretype.to_param}, valid_session
      }.to change(Hardwaretype, :count).by(-1)
    end

    it "redirects to the hardwaretypes list" do
      hardwaretype = Hardwaretype.create! valid_attributes
      delete :destroy, {:id => hardwaretype.to_param}, valid_session
      response.should redirect_to(hardwaretypes_url)
    end
  end

end
