require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RowemplsController do

  # This should return the minimal set of attributes required to create a valid
  # Rowempl. As you add validations to Rowempl, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "warehouse_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RowemplsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all rowempls as @rowempls" do
      rowempl = Rowempl.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rowempls).should eq([rowempl])
    end
  end

  describe "GET show" do
    it "assigns the requested rowempl as @rowempl" do
      rowempl = Rowempl.create! valid_attributes
      get :show, {:id => rowempl.to_param}, valid_session
      assigns(:rowempl).should eq(rowempl)
    end
  end

  describe "GET new" do
    it "assigns a new rowempl as @rowempl" do
      get :new, {}, valid_session
      assigns(:rowempl).should be_a_new(Rowempl)
    end
  end

  describe "GET edit" do
    it "assigns the requested rowempl as @rowempl" do
      rowempl = Rowempl.create! valid_attributes
      get :edit, {:id => rowempl.to_param}, valid_session
      assigns(:rowempl).should eq(rowempl)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Rowempl" do
        expect {
          post :create, {:rowempl => valid_attributes}, valid_session
        }.to change(Rowempl, :count).by(1)
      end

      it "assigns a newly created rowempl as @rowempl" do
        post :create, {:rowempl => valid_attributes}, valid_session
        assigns(:rowempl).should be_a(Rowempl)
        assigns(:rowempl).should be_persisted
      end

      it "redirects to the created rowempl" do
        post :create, {:rowempl => valid_attributes}, valid_session
        response.should redirect_to(Rowempl.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rowempl as @rowempl" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rowempl.any_instance.stub(:save).and_return(false)
        post :create, {:rowempl => { "warehouse_id" => "invalid value" }}, valid_session
        assigns(:rowempl).should be_a_new(Rowempl)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rowempl.any_instance.stub(:save).and_return(false)
        post :create, {:rowempl => { "warehouse_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rowempl" do
        rowempl = Rowempl.create! valid_attributes
        # Assuming there are no other rowempls in the database, this
        # specifies that the Rowempl created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Rowempl.any_instance.should_receive(:update_attributes).with({ "warehouse_id" => "1" })
        put :update, {:id => rowempl.to_param, :rowempl => { "warehouse_id" => "1" }}, valid_session
      end

      it "assigns the requested rowempl as @rowempl" do
        rowempl = Rowempl.create! valid_attributes
        put :update, {:id => rowempl.to_param, :rowempl => valid_attributes}, valid_session
        assigns(:rowempl).should eq(rowempl)
      end

      it "redirects to the rowempl" do
        rowempl = Rowempl.create! valid_attributes
        put :update, {:id => rowempl.to_param, :rowempl => valid_attributes}, valid_session
        response.should redirect_to(rowempl)
      end
    end

    describe "with invalid params" do
      it "assigns the rowempl as @rowempl" do
        rowempl = Rowempl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rowempl.any_instance.stub(:save).and_return(false)
        put :update, {:id => rowempl.to_param, :rowempl => { "warehouse_id" => "invalid value" }}, valid_session
        assigns(:rowempl).should eq(rowempl)
      end

      it "re-renders the 'edit' template" do
        rowempl = Rowempl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rowempl.any_instance.stub(:save).and_return(false)
        put :update, {:id => rowempl.to_param, :rowempl => { "warehouse_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rowempl" do
      rowempl = Rowempl.create! valid_attributes
      expect {
        delete :destroy, {:id => rowempl.to_param}, valid_session
      }.to change(Rowempl, :count).by(-1)
    end

    it "redirects to the rowempls list" do
      rowempl = Rowempl.create! valid_attributes
      delete :destroy, {:id => rowempl.to_param}, valid_session
      response.should redirect_to(rowempls_url)
    end
  end

end
